### ISSUE TITLE
To rotate svg figure of the chinese character by some angle through command of "HanziWriter.create"

### ISSUE THREAD

**Issue by andrewmung** [chanind/hanzi-writer-data#14]
Dear @chanind and all,

Thank you @chanind for your effort to to distribute this wonderful package of "Hanzi Writer"

May I know if command of "HanziWriter.create" is able to include rotating svg figure of the chinese character by some angle ? 

Or may I get your suggestion to achieve this matter ? 

Sorry, it may be naive to ask such question  

Thank you for your kind attention

**Comment by chanind** [comment]
Hi Andrew,

There's not a built-in way to do a rotation, but I think the easiest way to achieve that is to create a SVG element with a rotation on it, and then use that SVG element as the target for the HanziWriter instance. Something like the following should work:

in html:
```html
<svg transform="rotate(45)" id="target"></svg>
``` 

Then, in JS:
```javascript
HanziWriter.create('target', character, { width: 100, height: 100 })
```

**Comment by andrewmung** [comment]
Hi @chanind,
Thank you very much
