### ISSUE TITLE
【Question】What font family name used to generate this data ?

### ISSUE THREAD

**Issue by giappi** [chanind/hanzi-writer-data#6]
Dear @chanind,
I'm very interested in the strokes of the characters in this data. I saw it in many place but I don't know the font family name. Can I know the font that you used to make these characters in this data?
Thank you.

**Comment by chanind** [comment]
All the data comes from [Make me a Hanzi](https://github.com/skishore/makemeahanzi), which derived it from [Arphic PL KaitiM GB](https://apps.ubuntu.com/cat/applications/precise/fonts-arphic-gkai00mp/)
  and [Arphic PL UKai](https://apps.ubuntu.com/cat/applications/fonts-arphic-ukai/).. More info here: https://github.com/skishore/makemeahanzi#sources

**Comment by giappi** [comment]
I get it. Thank you very much.
